<a href="https://colab.research.google.com/github/lizard25/Completed-courses-list/blob/main/robotArmFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
""" Kinematic chain of a robot arm (planar)
    Assignment
"""

' Kinematic chain of a robot arm (planar)\n    Assignment \n'


![](https://github.com/eraldoribeiro/assignment_robotarm2D/blob/main/robotArm01.png?raw=1)
*Figure 1*: A two-dimensional articulated arm. The articulated structure has 3 local coordinate frames each one centered at a joint. For each part, the local x-axis is aligned with the part.  

Consider the arm structure shown in Figure 1. Assume the following values for the arm configuration:
- The location of the first joint (i.e., the one that is attached to the ground support) is ${\bf p}_1 = \left(3,2\right)^\mathsf{T}$.
- The lengths of the parts are $L_1 = 5$ and  $L_2 = 8$.

In [2]:
import numpy as np
import math as mph

In [3]:
def makeTransformationMatrix(phi: float, translation:tuple):
  return np.array([[np.cos(phi), -np.sin(phi), translation[0]],
                   [np.sin(phi), np.cos(phi), translation[1]],
                   [0,0,1]])
print(makeTransformationMatrix(0,(0,0)))
print(makeTransformationMatrix(45,(1,2)))

[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 0.52532199 -0.85090352  1.        ]
 [ 0.85090352  0.52532199  2.        ]
 [ 0.          0.          1.        ]]


### Question 1

Write the matrices that represent the local coordinate frames $\mathcal F\{1\}$, $\mathcal F\{2\}$, and $\mathcal F\{3\}$. These frames are indicated in green in Figure 1. The transformation matrices you need to write are $T_{0,1}$, $T_{1,2}$, and $T_{2,3}$.

In [4]:
# Answer goes here. Add more code/markdown cells as needed
L1 = 5
L2 = 8
phi1 = np.pi / 8
phi2 = np.pi / 4
phi3 = 0
T01 = makeTransformationMatrix(phi1,(3,2))
T12 = makeTransformationMatrix(phi2,(L1,0))
T23 = makeTransformationMatrix(phi3,(L2,0))
print(T01)
print(T12)
print(T23)

[[ 0.92387953 -0.38268343  3.        ]
 [ 0.38268343  0.92387953  2.        ]
 [ 0.          0.          1.        ]]
[[ 0.70710678 -0.70710678  5.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
[[ 1. -0.  8.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### Question 2

Write the matrices that represent each local frame w.r.t. the global frame $\mathcal F\{0\}$. The transformations you need to write are $T_{0,1}$, $T_{0,2}$, and $T_{0,3}$.

In [5]:
# Answer goes here. Add more code/markdown cells as needed
# T01 = makeTransformationMatrix(phi1,(3,2)) # included in last cell
T02 = T01 @ T12
T03 = T02 @ T23
print(T01)
print(T02)
print(T03)


[[ 0.92387953 -0.38268343  3.        ]
 [ 0.38268343  0.92387953  2.        ]
 [ 0.          0.          1.        ]]
[[ 0.38268343 -0.92387953  7.61939766]
 [ 0.92387953  0.38268343  3.91341716]
 [ 0.          0.          1.        ]]
[[ 0.38268343 -0.92387953 10.68086512]
 [ 0.92387953  0.38268343 11.30445342]
 [ 0.          0.          1.        ]]


### Question 3

Write the matrices that represent the local coordinate frames $\mathcal F\{1\}$, $\mathcal F\{2\}$, and $\mathcal F\{3\}$. These frames are indicated in green in Figure 1. The transformation matrices you need to write are $T_{0,1}$, $T_{1,2}$, and $T_{2,3}$.

In [6]:
# Answer goes here. Add more code/markdown cells as needed
print(T01)
print(T12)
print(T23)



[[ 0.92387953 -0.38268343  3.        ]
 [ 0.38268343  0.92387953  2.        ]
 [ 0.          0.          1.        ]]
[[ 0.70710678 -0.70710678  5.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
[[ 1. -0.  8.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### Question 4

Using the transformations from the previous questions, calculate the global coordinates of the middle point of each part of the robot arm when $\phi_1 = \pi/8$ and $\phi_2 = \pi/4$. Hint: the location of the middle point of part 1 is $(\frac{L_1}{2},0)^\mathsf{T}$ (w.r.t. frame $\mathcal F\{1\}$).

In [15]:
# Answer goes here. Add more code/markdown cells as needed
def midpoint(pa:np.array, pb:np.array):
  return np.array([(pa[0]+pb[0])/2, (pa[1]+pb[1])/2])


p0 = np.array([0,0,1])
L1 = 5
L2 = 8
phi1 = np.pi / 8
phi2 = np.pi / 4
phi3 = 0

p1 = T01 @ p0
print("points:\n",p1)
p2 = T02 @ p0
print(p2)
p3 = T03 @ p0
print(p3)

print("midpoints\n",midpoint(p1,p2))
print(midpoint(p2,p3))

points:
 [3. 2. 1.]
[7.61939766 3.91341716 1.        ]
[10.68086512 11.30445342  1.        ]
midpoints
 [5.30969883 2.95670858]
[9.15013139 7.60893529]


### Question 5

Using the transformations from the previous questions, calculate the global coordinates of all the joint points and the end-effector location when $\phi_1 = \pi/4$ and $\phi_2 = \pi/8$.

In [16]:
# Answer goes here. Add more code/markdown cells as needed
L1 = 5
L2 = 8
phi1 = np.pi / 4
phi2 = np.pi / 8
phi3 = 0
T01 = makeTransformationMatrix(phi1,(3,2))
T12 = makeTransformationMatrix(phi2,(L1,0))
T23 = makeTransformationMatrix(phi3,(L2,0))
T02 = T01 @ T12
T03 = T02 @ T23
p1 = T01 @ p0
print("points:\n",p1)
p2 = T02 @ p0
print(p2)
p3 = T03 @ p0
print(p3)


points:
 [3. 2. 1.]
[6.53553391 5.53553391 1.        ]
[ 9.59700136 12.92657017  1.        ]


### Question 6

Write the matrix that represents the coordinate frame of the end effector w.r.t. frame  $\mathcal F\{1\}$, i.e., $T_{1,3}$

In [17]:
# Answer goes here. Add more code/markdown cells as needed
T13 = T12 @ T23
print(T13)


[[ 0.92387953 -0.38268343 12.39103626]
 [ 0.38268343  0.92387953  3.06146746]
 [ 0.          0.          1.        ]]


### Question 7

Write the matrix that represents the coordinate frame $\mathcal F\{1\}$ w.r.t. to the frame of the end effector

In [18]:
# Answer goes here. Add more code/markdown cells as needed
T31 = np.linalg.inv(T13)
print(T31)



[[  0.92387953   0.38268343 -12.61939766]
 [ -0.38268343   0.92387953   1.91341716]
 [  0.           0.           1.        ]]
